version: "3.7"

networks:
  lan_access:
    driver: bridge

services:
  app:
    restart: always
    networks:
      - lan_access
      - default
    environment:
      - verbose=1
      - mqtt__address=mosquitto
      - mqtt__port=1883
      - mqtt__prefix=homeassistant
    build: .
  frontend:
    restart: always
    networks:
      - lan_access
    image: homeassistant/home-assistant
    ports:
      - "8123:8123"
    volumes:
      - ./docker/homeassistant:/config
      - ./shared:/shared
      - ./dev/serial/by-id/:/dev/serial/by-id/
  broker:
    extends:
      file: mosquitto-docker-compose/docker-compose.yaml
      service: mosquitto
    restart: always
    networks:
      - lan_access
