version: "3.7"
services:
  app: 
    network_mode: "host"  
    environment:
      - verbose=1
      - mqtt__address=mosquitto
      - mqtt__port=1883
      - mqtt__prefix=homeassistant
    build: .
  frontend:
    image: homeassistant/home-assistant
    ports:
      - "8123:8123"
    volumes:
      - ./docker/homeassistant:/config
      - ./shared:/shared
      - ./dev/serial/by-id/:/dev/serial/by-id/
  broker:
    extends:
        file: mosquitto-docker-compose/docker-compose.yaml
        service: mosquitto